export const boardData = [
  {
    id: 1,
    status: "TO DO",
    type: "SITEPLAN",
    title: "Mobile Siteplan",
    description: "Create a siteplan for application mobile and some userflow",
    attachments: 3,
    flag: "danger",
    date: "Mar 23",
    comments: 3,
  },
  {
    id: 2,
    status: "TO DO",
    type: "WIREFRAME",
    title: "Wireframe Aplikasi Course",
    description: "",
    attachments: 3,
    flag: "danger",
    date: "Mar 23",
    comments: 3,
  },
  {
    id: 3,
    status: "REVIEW",
    type: "DESIGN SYSTEM",
    title: "Design System",
    description: "Review Design system for website course",
    attachments: 3,
    flag: "danger",
    date: "Mar 23",
    comments: 3,
  },
  {
    id: 4,
    status: "DOING",
    type: "SITEPLAN",
    title: "Mobile Siteplan",
    description: "Create a siteplan for application mobile and some userflow",
    attachments: 3,
    flag: "danger",
    date: "Mar 23",
    comments: 3,
  },
  {
    id: 5,
    status: "REVIEW",
    type: "Color",
    title: "Color Pallete",
    description: "Review Design system for website course",
    attachments: 3,
    flag: "danger",
    date: "Mar 23",
    comments: 3,
  },
  {
    id: 6,
    status: "COMPLETE",
    type: "UI Design",
    title: "Create 3 Landing Page for Course",
    description: "Create a siteplan for application mobile and some userflow",
    attachments: 3,
    flag: "danger",
    date: "Mar 23",
    comments: 3,
  },
];

export const navbar = [
  { name: "Activity", to: "", icon: "/assets/icons/menu-link-2.png" },
  {
    name: "My Task",
    to: "",
    icon: "/assets/icons/menu-link-1.svg",
    divider: true,
    notifications: 15,
  },
  { name: "Dashboard", to: "", icon: "/assets/icons/menu-link-3.png" },
  {
    name: "Project",
    to: "",
    icon: "/assets/icons/menu-link-7.png",
    active: true,
    child: [
      {
        name: "Ninja Web Design",
        to: "",
        icon: "/assets/icons/menu-link-8.png",
        active: true,
      },
      {
        name: "Mobile Application",
        to: "",
        icon: "/assets/icons/menu-link-8.png",
      },
    ],
  },
  { name: "Calender", to: "", icon: "/assets/icons/menu-link-4.png" },
  { name: "Teams", to: "", icon: "/assets/icons/menu-link-5.png" },
  { name: "Analytics", to: "", icon: "/assets/icons/menu-link-6.png" },
];

export const secondaryNav = [
  { name: "Settings", to: "", icon: "/assets/icons/gear.png" },
  { name: "Help", to: "", icon: "/assets/icons/help.png" },
];
